//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CHANNEL
    {
        public int ID { get; set; }
        public string Tilte { get; set; }
        public string TitleImg { get; set; }
        public int ParentID { get; set; }
        public int Levels { get; set; }
        public bool IsDisplay { get; set; }
        public int TypeId { get; set; }
        public int DisplayOrder { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateUser { get; set; }
    }
}
